name: Metrics

on:
  schedule: [{ cron: "0 0 * * 1" }]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Maeva-RODRIGUES
          template: classic
          base: header, repositories
          config_timezone: Europe/Paris

          plugin_languages: yes
          plugin_languages_ignored: html # si tu veux l'enlever
          plugin_languages_limit: 6

          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: mastered

          plugin_dependencies: yes
          plugin_dependencies_section: frameworks

