name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Génération quotidienne
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Maeva-RODRIGUES
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v4 # Mise à jour vers v4
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.svg

